package com.malefeng.mychat.bean.entity;

import lombok.Data;
import lombok.experimental.Accessors;

import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.util.Date;

/**
 * @author mlf
 * @Date Wed Mar 10 14:55:02 CST 2021
 */
@Table(name = "t_user")
@Data
@Accessors(chain = true)
public class UserEntity implements Serializable {
    @Id
    @Column(name= "id")
    private Integer id;

    @Column(name= "user_code")
    private String userCode;

    @Column(name= "pass_word")
    private String passWord;

    @Column(name= "real_name")
    private String realName;

    @Column(name= "user_tel")
    private String userTel;

    @Column(name= "create_time")
    private Date createTime;

    @Column(name= "update_time")
    private Date updateTime;

    @Column(name= "open_user")
    private String openUser;

    @Column(name= "remark")
    private String remark;

    @Column(name= "del_flag")
    private Byte delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user
     *
     * @mbg.generated Wed Mar 10 14:55:02 CST 2021
     */
    private static final long serialVersionUID = 1L;
}